# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        mkdir src/rgbds
        wget -O src/rgbds/rgbds-0.9.1-linux-x86_64.tar.xz https://github.com/gbdev/rgbds/releases/download/v0.9.1/rgbds-0.9.1-linux-x86_64.tar.xz
        tar xf src/rgbds/rgbds-0.9.1-linux-x86_64.tar.xz -C src/rgbds
        rm src/rgbds/rgbds-0.9.1-linux-x86_64.tar.xz
    - name : Generate lexer/parser with ANTLR
      run: |
        sudo apt-get install -y default-jre
        curl -o antlr-4.13.2-complete.jar https://www.antlr.org/download/antlr-4.13.2-complete.jar
        java -Xmx500M -cp ./antlr-4.13.2-complete.jar org.antlr.v4.Tool \
          -Dlanguage=Python3 \
          -visitor \
          -o src/generated \
          -Xexact-output-dir \
          src/grammar/penguin.g4
        ls -R src/generated
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        PYTHONPATH=. flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        PYTHONPATH=. flake8 . --count --exit-zero --statistics
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest
      working-directory: ${{ github.workspace }}
